### ISSUE TITLE
Estruturar Selos do Mapa da Saúde

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#126]
## **Objetivo**

**Como** designer  
**Quero** estruturar os Selos do Mapa da Saúde
**Para** contribuir na definição da Jornada das pessoas usuárias

## **Contexto**

Durante a estruturação da AI do Mapa da Saúde, surgiu a necessidade de elaborar as Regras dos Selos do Mapa. A ação visa contribuir para definição da Jornada de criação, aplicação e gerenciamento dos Selos pelas pessoas usuárias.

## **Escopo**
- [ ] Inception dos Selos
- [ ] Estruturar as Regras de Negócio dos Selos
- [ ] Desenvolver a AI dos Selos
- [ ] Criar a Jornada das Pessoas Usuárias

## Observações
https://www.figma.com/file/rMFUNO9FjkBxejQRlinCsb/AI-Mapa-da-Saúde-V1.1?node-id=0%3A1

**Comment by RaniGub** [comment]
Em conversa com Uirá, foi esclarecido que parte desse processo já está em andamento. Quando priorizada a demanda, o DesignLab deve ter essa aproximação com o @rmadev-master e demais envolvidos para estruturação e consolidação dos Selos.

**Comment by rafaelmassuncao** [comment]
Um documento inicial foi estruturado e está em fase de análise.
