### ISSUE TITLE
AI do Fluxo de Cadastro Integrado

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#132]
## **Objetivo**

**Como** designer  
**Quero** mapear taxonomias
**Para** nortear os campos do Fluxo de Cadastro

## **Contexto**

É necessário visualizar como se dá a experiência de quem faz o cadastro de perfil vindo pelo iSUS e pelo Mapa da Saúde através do idSaúde. Após isso, uma proposta de cadastro integrada será traçada, considerando a taxonomia das soluções envolvidas, assim como os bancos de dados.

## **Escopo**

- [x] 1 Jornada de cadastro pelo iSUS
- [x] 2 Jornada do cadastro pelo Mapa da Saúde
- [x] 2.1 Cadastro de complemento de informações no Mapa
- [ ] 3 Nova proposta de Fluxo de Cadastro integrada
- [ ] 3.1 Definição de campos obrigatórios para cadastro na primeira experiência
- [ ] 3.2 Definição das opções dos campos do cadastro
- [ ] Validação com Uirá
- [ ] Ajustes
- [ ] 4 Prototipação da experiência
- [ ] Validação com Uirá
- [ ] Ajustes
- [ ] Avaliar tarefa #380 para conclusão
- [ ] Avaliar tarefa #304 para conclusão
- [ ] Avaliar tarefa 60 para conclusão

## Observações
https://www.figma.com/file/I9BbXtJHHe3prnlEN8Iofk/Fluxo-de-Cadastro-e-Roadmap?node-id=0%3A1
