### ISSUE TITLE
AI Mapa da Saúde (V1.2)

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#134]
## **Objetivo**

**Como** designer  
**Quero** fazer o levantamento da AI do Mapa da Saúde
**Para** nortear uma nova experiência para pessoa usuária

## **Contexto**

Considerando o relacionamento de taxonomia do Fluxo de Cadastro (#87), faz-se necessário o levantamento da atual AI do Mapa da Saúde. As informações terão relevância tanto para o relacionamento dos campos nas diversas soluções digitais quanto para a nova proposta da AI do Mapa da Saúde.  

## **Escopo**

- [ ] 1 Sincronizar AI do Mapa da Saúde (Ambiente de Homologação) com a V1.1
- [ ] 2 Verificar as tarefas relacionadas com a AI do Mapa identificadas na V1.1
- [ ] 2.1 AI de nível 1 das opções do Menu Superior
- [ ] 2.2 AI de nível 2 das opções do Menu Superior
- [ ] 2.2.1 AI de todas as instâncias (Entidades)
- [ ] 2.2.2 AI de todas as opções de Menu
- [ ] Momento com stakeholders 1
- [ ] Definições após momento com stakeholders 1
- [ ] Propor nova AI
- [ ] Validar AI
- [ ] Adequar AI

WIP (Outro Épico)
- [ ] Traçar a Jornada das Pessoas Usuárias nas instâncias disponíveis (Entidades)

## Observações
Link da AI ainda não disponível, será acrescentado brevemente.

**Comment by RaniGub** [comment]
Foi iniciado um movimento com o Hacklab para traçar a AI ideal. Compreendemos que será um movimento de melhoria colaborativa. Só precisamos alinhar como essa evolução irá acontecer com a troca de experiência entre os times.
