### ISSUE TITLE
Jornada de Pessoas ESP | Bolsistas

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#136]
## **Objetivo**

**Como** gestor  
**Quero** visualizar as possíveis jornadas de bolsistas na ESP
**Para** permitir identificar fragilidades no Fluxo e oportunidade de melhorias

## **Contexto**

Visto o processo de publicação de edital à formação e avaliação de bolsistas que integram ou virão a fazer parte das soluções da ESP, é preciso visualizar como se dá esse fluxo e identificar o que pode ser melhorado.

## **Escopo**
- [x] Mapear jornada da Criação do Edital
- [x] Mapear jornada da Efetivação da Bolsa
- [x] Mapear jornada da Contratação/Outorga
- [x] Mapear jornada do Onboarding
- [x] Mapear jornada da Formação/Avaliação
- [x] Mapear jornada do desligamento do Bolsista
- [x] Criar board no Figma com a Jornada das Pessoas /ESP Bolsistas, com sugestões de aperfeiçoamento, quando for o caso.
- [ ] Refinar e Validar board com pessoas de contato.
- [ ] Compartilhar com os Stakeholders o board da Jornada.

## Observações

- board do figma onde estão sendo consolidados os dados coletados:

https://www.figma.com/file/TAKeXiXL7IoBftQlswRRHg/do-Edital-à-Outorga?node-id=0%3A1

**Comment by pauloamoreira** [comment]
.reunião com @MayaraMonte marcada para o dia 08/10, as 14h, para tratar sobre "Integração do Bolsista/Onboarding" e "formação e avaliação".

**Comment by pauloamoreira** [comment]
.reunião com @helenhilario  marcada para o dia 15/10, as 10h, para tratar sobre "Criação de Edital",
 "Efetivação da Bolsa" e "Contratação/Outorga".

**Comment by pauloamoreira** [comment]
.reunião marcada para dia 20/10, no período da tarde, com helen hilário, para refinar e validar o desenho inicial produzido a partir das primeiras informações fornecidas.

**Comment by pauloamoreira** [comment]
.reunião marcada para dia 20/10, no período da manhã, com @MayaraMonte , para refinar e validar o desenho inicial produzido a partir das primeiras informações fornecidas.
