### ISSUE TITLE
Fluxo para solicitação de demandas de Design ao DIT/ESP-CE

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#146]
## **Objetivo**

**Como** gestor  
**Quero** estruturar o fluxo de solicitação de demandas de Design ao DIT/ESP-CE
**Para** organizar as solicitações de apoio

## **Contexto**

Considerando o crescente índice de solicitação de demandas de Design ao DIT/ESP-CE, é preciso que seja estabelecido um fluxo formal para tais ações. Além disso, a estrutura servirá como um norteador para discutirmos uma proposta de ambiente para solicitação de demandas via digital com integração com iSUS e Central de Notificação.

Stakeholder: Washington

## **Escopo anterior**
Estabelecer Fluxo Geral (Paulo/Rani) - Prazo para Esboço 1 - 27/10/2021
- Estruturar um fluxo formal para solicitação de demandas ao DIT 
- Template de texto para formalização do pedido 
- Definir envolvidos em cada etapa (com e-mail)
- Estabelecer critérios de aceitação geral 
- Estabelecer critérios de aceitação para cada Laboratório 
- Estabelecer prazos para as etapas envolvidas no processo
- Estruturar esquema gráfico
- Parear com Washington

## **Novo Escopo**
Estabelecer Fluxo Experimental pelo Redmine (Wash/Rani)
- [ ] 1. Estruturar fluxo experimental
- [ ] 1.1 Padronização de formulário para formalização do pedido 
- [ ] 1.2 Definir integração com as possíveis entradas de solicitação
- [ ] 1.3 Estabelecer parametrizações 
- [ ] 1.4 Estruturar fluxo refinado
- [ ] 1.5 Publicizar

Estabelecer Fluxo Digital (Rani)
- [ ] Inception do Fluxo Digital para Demandas
- [ ] Estruturar relacionamentos com iSUS e Central de Notificações

## Observações
https://www.figma.com/file/QWDbpo9c4eXZfYRKpoW7dg/Fluxo-para-solicitação-de-demanda-DIT?node-id=0%3A1

**Comment by RaniGub** [comment]
Escopo alterado.

**Comment by RaniGub** [comment]
@gabrieladamarques Uirá pediu que você incluísse na sua agenda para conversamos.
