### ISSUE TITLE
Desenvolver o Projeto 'Oficina de Design de Serviços'

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#152]
## **Objetivo**

**Como** gestor  
**Quero** desenvolver o Projeto da Oficina de Design de Serviços Públicos
**Para** ser aplicada aos setores da ESP

## **Contexto**

Considerando os resultados positivos obtidos na Oficina de Design de Serviços Públicos realizada em parceria com a Sepos, serão realizadas novas Oficinas de Design de Serviços Públicos, desta vez, voltadas para os setores da ESP, de modo a refinar os problemas/dores de cada setor, verificar o status do atendimento às solicitações já realizadas, diagnosticar novas demandas e nortear a tomada de decisões da gestão. Durante a Oficina, serão criadas agendas de reuniões com os setores, para dar prosseguimento no desenvolvimento das soluções diagnosticadas.

## **Escopo**
- [ ] 1 Consolidar formato da II Oficina de Design de Serviços Públicos
- [ ] 1.1 Definir conteúdos e metodologia
- [ ] 1.2 Produzir/atualizar/adaptar materiais didáticos
- [x] 1.3 Estruturar Metodologia da Pré-Oficina
- [x] 1.3.1 Definir documento de mapeamento de demandas com áreas
- [x] 1.3.2 Definir documento de roteiro dos encontros com áreas
- [ ] 1.3.3 Construir espaço de estruturação das demandas (descrição, tipos, expectativas de prazo, projetos, soluções, etc.)
- [ ] 1.4 Validar com Stakeholders
_____
- [ ] 2. Realizar Oficina
- [ ] 3 Construir Agenda de Reuniões segmentadas (com  cada área) 2022.
- [ ] Consolidar documento do Projeto

## Observações
Stakeholder: Uirá
https://docs.google.com/document/d/1Xqjr1KejwOvVsG--3CRSn7aT9Rd3mYVcuFA3UI4u0ds/edit?usp=sharing

**Comment by RaniGub** [comment]
Esse Projeto será acompanhado pelo time de Gestão de Projetos. O modelo do despacho anexado também pode dar apoio as discussões iniciais. Essa tarefa será finalizada.
https://docs.google.com/document/d/1m9_7yWXpVX6vbTwDZJJj1GXk71GrcTsz1j9-665sW2Y/edit
