### ISSUE TITLE
Testes de usabilidade do Mapa da Saúde

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#155]
## **Objetivo**

**Como** designer
**Quero** realizar testes de usabilidade no Mapa da Saúde
**Para** contribuir na construção de uma melhor experiência

## **Contexto**
É preciso realizar testes de usabilidade com as principais Jornadas do Mapa da Saúde. Dessa forma será possível identificar gaps na experiência da pessoa usuária e gerar relatórios de sugestões de melhorias.

## **Escopo**

- [ ] 1. INSCRIÇÕES E/OU RESULTADOS
- [ ] 1.1 EDITAL 23
- [ ] 1.1.1 Jornada da Inscrição no Edital 23/2021
- [x] 1.1.2 Inscrição no Edital 23 2A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.3 Inscrição no Edital 23 3A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.4 Inscrição no Edital 23 4A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.5 Inscrição no Edital 23 5A - Pessoa com cadastro acessando o link do Mapa da Saúde
- [x] 1.1.6 Inscrição no Edital 23 6A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.7 Inscrição no Edital 23 7A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.8 Inscrição no Edital 23 8A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.9 Inscrição no Edital 23 9A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.10 Inscrição no Edital 23 10A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.11 Inscrição no Edital 23 11A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.12 Inscrição no Edital 23 12A - Pessoa sem cadastro acessando o link do Mapa da Saúde
- [x] 1.1.13 Inscrição no Edital 23 13A - Pessoa sem cadastro acessando o link do Mapa da Saúde
...
- [x] 1.2 EDITAL 26
- [x] Jornada da Inscrição no Edital 26/2021
- [x] 1.2.1 Inscrição no Edital 26 14A - Pessoa com cadastro acessando o link direto da oportunidade
- [x] 1.2.2 Inscrição no Edital 26 15A - Pessoa com cadastro acessando o link direto da oportunidade
- [x] 1.2.3 Inscrição no Edital 26 16A - Pessoa com cadastro acessando o link direto da oportunidade
- [x] 1.2.4 Inscrição no Edital 26 17A - Pessoa com cadastro acessando o link direto da oportunidade
...
- [ ] 1.3 PRÊMIO MUNICÍPIO INOVADOR
- [ ] 1.3.1 Jornada da Inscrição de Avaliadores
- [ ] 1.3.1.1 Teste de usabilidade
- [x] 1.3.2 Jornada da Inscrição da Iniciativa
- [ ] 1.3.2.1 Teste de usabilidade
- [x] 1.3.3 Jornada da Adesão do Município
- [ ] 1.3.3.1 Teste de usabilidade
- [ ] 1.3.4 Refinar Jornadas (Daniel e Thaís)
...
- [ ] 2. AVALIAÇÕES
...
- [ ] 3. GESTÃO
...
- [x] 4 MODELO PARA PARAMETRIZAÇÃO DAS JORNADAS
- [x] 4.1 Paramentrizar Jornada das Inscrições
- [ ] 4.2 Paramentrizar Jornada das Avaliações
- [ ] 4.3 Paramentrizar Jornada de Gestão
...
- [x] 5 DEFINIR MODELO DE RELATÓRIO

## **Outras Informações**
Documento principal:
https://docs.google.com/document/d/1O7qgzia8u2bEowAVfgve61yrEHlhGo9nsAOu0eUo_kc/edit#
Fluxo de testes:
https://www.figma.com/file/M70kqwduTAEkDtICICmDas/Fluxo-dos-Testes-de-Usabilidade?node-id=0%3A1

**Comment by RaniGub** [comment]
@gabrieladamarques queria conversar com você depois sobre esse card. Os testes serão permanentes e imagino que ele evolua de um épico para uma iniciativa.

**Comment by gabrieladamarques** [comment]
@RaniGub na versão final da EAP do Mapa que foi validada a gente não tem o épico Testes de usabilidade. Mas faz sentido que, na organização da board do Designlab, vcs entendam os testes como um épico/iniciativa. Acho que pro nível de organização de vocês faz sentido agrupar essas atividades como épico ou até como iniciativa.
Mas para o acompanhamento da execução da EAP, o que estou fazendo é associar cada cards de testes aos itens específicos (épicos da EAP) que eles pretendem testar. Por exemplo, os que foram feitos até agora atendem ao épico Inscrição de candidatos, que fica em Plataforma interativa>Customização>Gerenciamento de editais e eventos, e aí estou incluindo eles lá dentro desse épico do board do Mapa da Saúde. Faz sentido?

**Comment by RaniGub** [comment]
Isso Gabi, é só para nosso acompanhamento mesmo.

**Comment by uira** [comment]
@gabrieladamarques E sim, faz muito sentido a forma que você tá fazendo, @gabrieladamarques .

Os testes, assim como código e design, são etapas do processo de desenvolvimento que vão resultar nas entregas. 

Então, na prática, todos os pacotes de trabalho terão etapas de Design e Testes/QA

**Comment by RaniGub** [comment]
Organizando documento principal para retomada da consolidação dos testes 8A, 9A e 10A | Edital 23/2021.

**Comment by RaniGub** [comment]
Desde o início dos testes vínhamos fazendo a gravação para consolidação numa conta pessoal, que perderá a funcionalidade nos próximos dias. Solicitei acesso a uma conta oficial da ESP para realização das gravações, no entanto a mesma não logava (nutic@tmp.esp.ce.gov.br). Pedi ajuda ao Jardson em 03/12/2021 via Telegram, mas não obtive retorno. Hoje solicitei novo suporte via e-mail.

**Comment by RaniGub** [comment]
@MayaraMonte vamos acrescentar um espaço na nossa bateria de testes que contemple as histórias. Considerando a metodologia proposta na imersão do Mapas são elas que irão gerar o teste com base na necessidade das pessoas. Queria que você desse uma revisitada para propor a melhor forma da gente abordar isso no documento.

**Comment by RaniGub** [comment]
Ah @MayaraMonte amanhã você conversa com a @caldy94 para fazer uma pré-validação das histórias [dessa board](https://www.figma.com/file/pXE9G20Xe4v7LwaAEyduzr/Redesign-Mapas---Imers%C3%A3o?node-id=0%3A1) que podem integrar a bateria de futuros testes.

**Comment by RaniGub** [comment]
@MayaraMonte por gentileza, atualize o escopo desse Épico com base nas novas projeções de testes. Aproxime a @caldy94 para essa atualização.

**Comment by pauloamoreira** [comment]
.a projeção de testes só será possível após a reestruturação do time do Mapa. aguardaremos orientações da @thaistoscano para retomar essa tarefa.
