### ISSUE TITLE
Arquitetura da Informação de funcionalidades das Soluções Digitais do SUS/CE | Integrações

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#204]
## **Objetivo**

**Como** designer
**Quero** propor a AI de funcionalidades das soluções digitais do SUS/CE
**Para** sugerir camadas de integração

## **Contexto**
Devemos identificar por meio da AI de funcionalidades, as oportunidades de integração para proporcionar a pessoa usuária o acesso a funções essenciais e integradas pelas soluções digitais que permeiam o SUS/CE.

## **Escopo**

- [ ] 1 Mapa da Saúde
- [ ] 2 iSUS
- [ ] 2.1 QualiQuiz
- [ ] 4 ESP Virtual
- [ ] 5 Sagu
- [ ] 6 Central de Informações do SUS
- [ ] 7 Proposta de integração V1.0 | Mapa da Saúde e iSUS
- [ ] 7.1 Pareamento BA Mapa | Integrações
- [ ] 7.2 Pareamento BA iSUS | Integrações
- [ ] 8 Brainstorming de integrações V1.0

**Comment by RaniGub** [comment]
@uira fico imaginando se ainda faz sentido continuarmos com essa tarefa... ai voltamos aquele papo de estarmos limitados às funcionalidades e não fazermos o processo de descobrir as potencialidades dos produtos. 

Nesse sentido, tanto para o caminho de entendermos quais passos a seguir com o que já se tem de tarefas e como integrá-las, quanto para traçar a projeção de entregas nos projeto... teremos o momento de pensar nas integrações com os times e priorizações através das inceptions.

Por outro lado, faz sentido se for nosso objetivo traçar o que dá pra gente fazer com o que tem e ir versionando na medida que os produtos evoluam. Para que o esquema não seja visto como um limitador, mas como algo consultivo pros times: "Ah isso é possível fazer integrando isso e aquilo outro..." - viajando aqui :/ - Acho que a história para isso seria:

Eu como integrante do time de produto do Felicilab
Quero visualizar as oportunidades de integração entre as funcionalidades dos produtos da ESP/CE
Para sugerir possibilidades de integrações entre as histórias dos usuários

**Comment by RaniGub** [comment]
Esse épico e issues relacionadas serão finalizados devido ao novo movimento integrado.
