### ISSUE TITLE
Apoiar o processo de Redesign do Mapas

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#214]
## **Objetivo**

**Como** designer
**Quero** apoiar o processo de Redesign do Mapas com o HackLab
**Para** sugerir a melhoria da UI com base nos achados de UX do Mapa da Saúde

## **Contexto**
Iniciamos um processo de diálogo com o HackLab em 01/02/2021 para que possamos apoiar o Redesign do Mapas. Para isso, estamos organizando um Grupo de Governança envolvendo os times do HackLab e da ESP/CE. É importante que todos os momentos sejam gravados e uma ata com resumo dos tópicos tratados sejam disponibilizada para os envolvidos. Os momentos terão como objetivos:
a) Dar suporte ao fluxo de experiências das entidades e outras ações
b) Sugerir pontos de melhorias na interface

Fluxo das reuniões: 
Diálogo entre HackLab (Patrick) e DesigbLab (Paulo) para agendamento semanal -> Iniciar gravação -> Atualizar ata com resumo dos tópicos tratados -> Informar no grupo sobre atualização da ata (com link da gravação)

## **Escopo**
- [x] Desenvolver modelo da ata
- [x] Validar ata com Rani
- [ ] Desenvolver programação de Imersão UX

Reuniões
- [x] Reunião 01: 03/02/22 - 15h-17
- [x] Reunião 02: 10/02/22 - 15h-17
- [x] Reunião 03: 17/02/22 - 15h-17
- [x] Reunião 04: 24/02/22 - 15h-17
- [x] Reunião 05: 03/03/22 - 15h-17

## **Outras Informações**
1 - [Cronograma HackLab](https://docs.google.com/spreadsheets/d/11sxw_3RumQqYx9MTuhiaU-TTKqNxhrnrfr40XlKYHP4/edit?usp=sharing)
2 - [Pasta Compartilhada](https://drive.google.com/drive/folders/1FSYdbkhCSgPwpvEkcH_Nd85-DyZ3Cwi0?usp=sharing)
3 - [Atas](https://docs.google.com/document/d/15T7RVk5T56SHwBMnRJNKd6sgclfj7e5RNQ2YED-VmDU/edit?usp=sharing)
4 - [Metodologia](https://www.figma.com/file/VLUI43dTr5ivr3zV8sWwHP/Fluxo-de-pareamentos-com-HackLab---Redesign-Mapas?node-id=0%3A1)
5 - [Relação das funcionalidades e Jornadas](https://www.figma.com/file/FgxbetO9cfZ0KBPJFVNcXX/Mapeamento-de-fluxo-de-intera%C3%A7%C3%A3o%2Fjornadas-do-Mapas-Culturais?node-id=0%3A1)
6 - [Documentação Mapas Culturais](http://docs.mapasculturais.org/)
7 - [Arquitetura Mapa da Saúde V1.1](https://www.figma.com/file/rMFUNO9FjkBxejQRlinCsb/AI-Mapa-da-Sa%C3%BAde---V1.1?node-id=0%3A1)

**Comment by RaniGub** [comment]
@pauloamoreira atualizei o Épico e relacionei as tarefas que já haviam sido realizadas. Adicionei o Reunião 04 também para esse sprint.

**Comment by RaniGub** [comment]
O Épico será finalizado. Aguardamos a compreensão de como o movimento continuará com articulação com a comunidade e Hacklab para a criação de um novo.
