### ISSUE TITLE
Oficinas de Design para Políticas Públicas - SEPOS

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#225]
## **Objetivo**

**Como** designer
**Quero** apoiar a construção das Políticas Estaduais de Saúde
**Para** nortear a elaboração dos Plano Estaduais das Políticas Públicas do Ceará (2022-2023)

## **Contexto**

- A Secretaria Executiva de Políticas de Saúde - SEPOS/SESA, solicitou à Superintendência da ESP/CE, por meio do ofício 10/2022, apoio do DesignLab/Felicilab para facilitação na construção das Políticas Estaduais de Saúde. O pedido partiu da experiência na I Oficina de Design de Serviços Públicos, realizada com a Sepos em Ago/2021. Foi definido que a Adins será a responsável pela condução do processo e o DesignLab entrará como apoio.

## **Escopo**

1. Apoiar a Construção da Política Estadual de Prevenção e Proteção às mulheres, crianças e adolescentes 
- [x] 1.1 Refinar a demanda com Marley Carvalho da Sepos
- [x] 1.2 Confirmar datas de realização
- [x] 1.3  Coletar informações complementares e documentos norteadores
- [x] 1.4 Estudar materiais e documentos de referência da Política fornecidos pela Coordenadoria
- [x] 1.5 Preparar board para oficina
- [x] 1.6 Preparar formulário de avaliação
- [x] 1.7 Fornecer instruções e orientações para equipe de apoio da Sepos
- [x] 1.8 Realizar oficina (07/03)
- [x] 1.8.1 Realizar oficina (14/03)
- [x] 1.9 Consolidar e compartilhar dados produzidos
- [x] 1.10 Realizar avaliação

2. Apoiar a Construção da Política Estadual de Transplante
- [x] 2.1 Refinar a demanda com Camila Mendes da Sepos
- [x] 2.2 Confirmar datas de realização
- [x] 2.3  Coletar informações complementares e documentos norteadores
- [x] 2.4 Estudar materiais e documentos de referência da Política fornecidos pela Coordenadoria
- [x] 2.5 Preparar board para oficina
- [x] 2.6 Preparar formulário de avaliação
- [x] 2.7 Fornecer instruções e orientações para equipe de apoio da Sepos
- [x] 2.8 Realizar oficina (16/03)
- [x] 2.8.1 Realizar oficina (23/06)
- [x] 2.8.2 Realizar oficina (30/06)
- [x] 2.9 Consolidar e compartilhar dados produzidos
- [x] 2.10 Realizar avaliação

3. Apoiar a Construção da Política da Pessoa com Deficiência
- [x] 3.1 Refinar a demanda com Juliana Donato da Sepos
- [x] 3.2 Confirmar datas de realização
- [x] 3.3  Coletar informações complementares e documentos norteadores
- [x] 3.4 Estudar materiais e documentos de referência da Política fornecidos pela Coordenadoria
- [x] 3.5 Preparar board para oficina
- [x] 3.6 Preparar formulário de avaliação
- [x] 3.7 Fornecer instruções e orientações para equipe de apoio da Sepos - equipe de tradutores
- [x] 3.8 Fornecer instruções e orientações para equipe de apoio da Sepos - equipe de apoio
- [x] 3.9 Realizar oficina (07/03)
- [x] 3.9.1 Realizar oficina (09/03)
- [x] 3.9.2 Realizar oficina (10/03)
- [x] 3.10 Consolidar e compartilhar dados produzidos
- [x] 3.11 Realizar avaliação 

## Observações
Pessoas de Contato:
Política de Prevenção e Proteção às Mulheres, crianças e adolescentes - Marley Carvalho
Política de Transplante: Camila Mendes
Política da Pessoa com Deficiência: Juliana Donato
![Captura de Tela 2022-02-15 às 09 18 38](https://user-images.githubusercontent.com/79097920/154060768-8c95dfd4-b8eb-4b8e-83e4-b28eb9c0d4d3.png)

**Comment by RaniGub** [comment]
Política Estadual de Transplante
Dia 1: 09/03 ou 10/03
Dia 2: 16/03 ou 17/03

Política Estadual de Prevenção e Proteção às mulheres, crianças e adolescente
Dia 1: 04/03
Dia 2: 11/03

Política da Pessoa com Deficiência
Dia 1: 07/03
Dia 2: 09/03
Dia 3: 10/03

As datas da Política da Pessoa com Deficiência e Política Estadual de Transplante estão conflitando. @pauloamoreira entrou em contato com a Juliana para informar. A Juliana ficou de falar com a Secretária (Luziene) para acertarem as priorizações. Ficou de nos dar um retorno hoje (16/02).

**Comment by pauloamoreira** [comment]
.a Camila Mendes, da oficina de transplante, indicou novas datas: 16/03 e 23/03

**Comment by RaniGub** [comment]
Épico encerrado.
