### ISSUE TITLE
Inception do Projeto Mapas e Soluções

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#294]
## **Objetivo**

**Como** designer  
**Quero** mobilizar os times de projeto e produtos
**Para** realização da Inception do Mapas e Soluções

## **Contexto**
A Inception foi realizada com Educação Permanente, Residência Multiprofissional, DIDES, RH, GEPRO e Secretaria Acadêmica. A Inception finalizou nas histórias. Agora é necessário que os times revisem os achados e concluam a Board que dará o direcionamentos das ações para as próximas semanas.

## **Escopo**

- [x] Mobilizar Encontro 1 da Inception (Data:01/04/2022)
- [x] Mobilizar Encontro 2 da Inception (Data:05/04/2022)
- [x] Mobilizar Encontro 3 da Inception (Data:07/04/2022)
- [x] Mobilizar Encontro 4 da Inception (Data:11/04/2022)
- [x] Mobilizar Encontro 5 da Inception (Data:12/04/2022)
- [x] Mobilizar Encontro 6 da Inception (Data:19/04/2022)
- [x] Mobilizar Encontro 7 da Inception (Data:28/04/2022)
- [x] Mobilizar Encontro 8 da Inception (Data:29/04/2022)

## Observações
https://www.figma.com/file/ab0B64s5aAxB79NLyhZuX0/Inception-Pr%C3%A9-Oficina-ESP-2022?node-id=0%3A1
