### ISSUE TITLE
Oficina de Design de Serviços ESP/CE 2022

### ISSUE THREAD

**Issue by pauloamoreira** [EscolaDeSaudePublica/DesignLab#317]
## **Objetivo**

**Como** designer de experiência
**Quero**formatar e realizar as pré-oficinas de Design de Serviços, junto às diretorias da ESP/CE, facilitadas pelo DesignLab.
**Para** garantir que os objetivos das oficinas sejam plenamente atendidos.

## **Contexto**

- Por ocasião da proximidade da realização das oficinas de Design de Serviços na ESP/CE, se faz necessário realizar pré-oficinas para a aplicação de Árvores de Problemas nas áreas: Educação e Extensão, Desenvolvimento Educacional, Inteligência em Saúde, Pesquisa em Saúde, Governança em Gestão e Inovação e Tecnologia, de modo a coletar informações que irão colaborar para as atividades previstas na oficina.

## **Escopo**

- [x] 1. Construir fluxo das pré-oficinas
- [x] 2. Estruturação metodológica das pré-oficinas
- [x] 3. Dispor instrumentos das pré-oficinas/oficinas
- [x] 4. Construir boards das pré-oficinas
- [x] 5.  Revisar modelo a vinculação das causas, problemas e consequências da árvore de gestão e governança
- [x] 6. Acompanhar processo de agendamento das pré-oficinas
- [x] 7. Validar proposta com stakeholders
- [x] 8. Realizar pré-oficina 1 - Governança e Gestão dia 18.05.2022
- [x] 8.1. Continuação pré-oficina 1 - Governança e Gestão dia 19.05.2022
- [x] 8.2. Sistematizar informações coletadas oficina de Governança e Gestão
- [x] 9. Realizar pré-oficina 2 - Desenvolvimento Educacional dia 25.05.2022
- [x] 9.1. Sistematizar informações coletadas oficina de Desenvolvimento Educacional
- [x] 10. Realizar pré-oficina 3 - Educação e Extensão dia 30.05.2022
- [x] 10.1. Continuação pré-oficina 3 - Educação e Extensão dia 03.06.2022
- [x] 10.2.  Sistematizar informações coletadas oficina de Educação e Extensão
- [x] 11. Realizar pré-oficina 4 - Inteligência em Saúde dia 31.05.200
- [x] 11.1. Sistematizar informações coletadas oficina de Inteligência e Saúde
- [x] 12. Realizar pré-oficina 5 - Inovação e Tecnologia dia 01.06.2022
- [x] 12.1. Sistematizar informações coletadas oficina de Inovação e Tecnologia
- [x] 13. Realizar pré-oficina 6 - Pesquisa em Saúde dia 06.06.2022
- [x] 13.1. Sistematizar informações coletadas oficina de Pesquisa em Saúde
- [x] 14. Estruturar o formato da Mandala de Governança
- [x] 15. Elaboração da Prestação de Contas - Produtos
- [x] 16. Elaboração da Prestação de Contas - Apoio à Governança
- [x] 17. Elaborar Match dos problemas priorizados nas pré-oficinas das áreas (Identificação de problemas transversais)
- [x] 18. Elaboração da Árvore Situacional da ESP
- [x] 19. Ambiente virtual para acompanhamento dos achados das Pré-Oficinas pelas áreas (Template WP)

## **Critérios de Aceitação**

- [x] Pré-oficinas de Design de Serviços na ESP/CE formatadas, realizadas e com resultados sistematizados
**Dado que** desejo conhecer o resultado das pré-oficinas de Design de Serviços  
**Quando** acessar os links disponíveis  
**então** poderei acessar os boards de trabalho e a sistematização dos resultados.

## Observações
board do figma em processo de construção: https://www.figma.com/file/WqnQDigTVM6tME4PRSdReP/Planejamento-Pr%C3%A9-oficina-e-Oficina---maio-2022?node-id=4%3A413

Pré-oficina 1 - Governança e Gestão - board da árvore de problemas, com sistematização de resultados:
https://www.figma.com/file/Dj0GKehXmSxjk3JvzYcqKV/Pr%C3%A9-Oficina-GOVERNAN%C3%87A-E-GEST%C3%83O?node-id=0%3A1

**Comment by RaniGub** [comment]
Tarefa convertida para Épico.

**Comment by pauloamoreira** [comment]
.escopo do épico revisado.

**Comment by RaniGub** [comment]
@elpadrejorge pvf crie as issues dos templates dos achados das pré-oficinas para as Áreas

**Comment by RaniGub** [comment]
@elpadrejorge marquei uma reunião nesta terça à tarde sobre a Produção da Oficina. Vamos atualizar o arquivo de acompanhamento e mapear o que é necessário entrar como issue aqui.

**Comment by RaniGub** [comment]
@elpadrejorge pfv alinhe com a @marameida um Épico de produção

**Comment by marameida** [comment]
Breve ata da reunião deprodução (31/05):
1. Formalizar local BECE: solicitado Ofício para DITEC;
2. Solicitação de coffee break : alinhado com Flaviane (80 pessoas)
3. Orçamento de kits: levantar preços dos seguintes materiais
- Crachá;
- Pasta plástica;
- Caneta;
- Caneca ou copo plástico;
- Bloco ou post it;
- Blusa;
- Adesivo;
4. Lista de Frequencias: impressões feitas
5. Ficha de inscrição: sugerido criar uma oportunidade no Mapas para levantar interesse prévio dos participantes. Alinhado com narrativas construção de texto explicativo.
6. Criar grupo whatshap: com os contatos, após deferimento das incrições;
7. Ver vinculação da frequencia com o Isus: alinhar com equipe do aplicativo;
8. Sobre elaboração de artefato da oficina: Sugerido que o mesmo siga metodologia da publicação do evento anterior.
9. Site do evento: definir que outras informações estarão descritas neste espaço.
10. Filtro da pasta de arquivos da oficina: alinhado com Jorge e Raniere que os arquivos serão atualizados, no entanto o registro das atividades seguirá pelo Zenhub.

**Comment by marameida** [comment]
Sugestão de Categorização das atividades (serão descritas em cards separados):
- Produção gráfica (banner, kits etc);
- Logística do evento (infraestrutura/materias, check-lists, llista de frequencias, local, coffee break);
- Comunicação/Divulgação (inscrição, grupos de comunicação, informes);
- Integração da oficina com Isus
- Elaboração de publicação sobre o evento;

**Comment by RaniGub** [comment]
Blz @marameida. Considere que o Épico é o #328 blz? Faça os desdobramentos pra gente enxergar melhor e saber o status de cada ponto discutido na reunião.

**Comment by RaniGub** [comment]
@pauloamoreira pfv, verificar nas 3 primeiras árvores se o ajuste das colunas entre causa, problema e consequência estão correspondendo.

**Comment by RaniGub** [comment]
Épico finalizado, será criado um novo épico para o pós-oficina.
