### ISSUE TITLE
Oficina de Design de Serviços ESP/CE 2022 - Produção

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#328]
## **Objetivo**

**Como** pessoa produtora da Oficina de Design ESP
**Quero** dispor de um kanban para acompanhamento das demandas de produção da Oficina
**Para** garantir que o momento seja realizado considerando todos os pontos

## **Contexto**

Por ocasião da proximidade da realização das oficinas de Design de Serviços na ESP/CE, se faz necessário realizar pré-oficinas para a aplicação de Árvores de Problemas nas áreas: Educação e Extensão, Desenvolvimento Educacional, Inteligência em Saúde, Pesquisa em Saúde, Governança em Gestão e Inovação e Tecnologia, de modo a coletar informações que irão colaborar para as atividades previstas na oficina.

## **Escopo**
LOGÍSTICA E ORGANIZAÇÃO
- [x] Lista de materiais necessários analógico para chegagem antes da oficina (elaboração de check-lists);
- [x] Elaboração e impressão de frequências;
- [x] Solicitação de cofee break (pré-oficinas e oficina final);
- [x] Fechamento com local (contato, visita, ofício)

COMUNICAÇÃO/DIVULGAÇÃO
- [x] Formulário de pré-inscrição (elaboração, validação, divulgação);
- [x] Informar as pessoas selecionadas sobre o início das oficinas;
- [x] Grupos de Comunicação Whatsapp (pós deferimento do mapeamento de intenção preenchido pelos colaboradores como oportunidade no Mapas;
- [x] Formulário de avaliação;

PRODUÇÃO GRÁFICA
- [x] Elaboração da arte para aplicação nos brindes e outros materiais (Felicilab/ASCOM);
- [x] Banner e adesivos (elaboração, orçamento e produção);
- [x] Kits de brindes (definição de itens, orçamento, produção);

**Comment by marameida** [comment]
Repassando aqui para o #328:
Sugestão de Categorização das atividades (serão descritas em cards separados):

-Produção gráfica (banner, kits etc);
-Logística do evento (infraestrutura/materias, check-lists, llista de frequencias, local, coffee break);
-Comunicação/Divulgação (inscrição, grupos de comunicação, informes);
-Integração da oficina com Isus
-Elaboração de publicação sobre o evento;

**Comment by RaniGub** [comment]
@elpadrejorge 
Criar issues de material padrão para oficina:
- Banner 90x120cm
- Card de divulgação para insta
- Cartaz A4 com QR Code
