### ISSUE TITLE
Novo fluxo de notificações do iSUS

### ISSUE THREAD

**Issue by ericabpinho** [EscolaDeSaudePublica/DesignLab#347]
**Eu como** Pessoa usuária do iSUS.
Quero Receber notificações do aplicativo.
Para Me manter atualizada sobre as soluções digitais e política de inovação da ESP. 

**CONTEXTO**
Por que notificaremos as atualizações de soluções mesmo no período de defeso?
Por que são plataformas de educação em saúde E produtos com concorrência no mercado, exceçoes previstas pela PGE. O time de Narrativas passa a ser responsável pelas notificações do iSUS, em uma fatia específica: a que diz respeito à política de inovação e às soluções digitais. Não podemos ficar nesse longo período sem nos relacionar com os usuários de nossas soluções, sem repassar a eles informações necessárias à continuidade do uso das soluções. Sem comunicação, interrompe-se o fluxo de experimentação das soluções. 
O fluxo de demandas da Escola segue da mesma forma: qualquer setor soliticita à Ascom, menos nós, que vamos publicar de forma direta. 
Deverão ser publicadas:
- Novas soluções digitais/política de inovação
- Novas funcionalidades do iSUS/Mapa/Elmo...
- Novas inscrições no Mapa: quando abrir/quando estiver próximo de fechar/no último dia. Essas notificações de inscrições no Mapa devem começar sendo feitas de forma manual e em seguida ser automatizadas. 

**ESCOPO**
- [x] Começar notificando sobre o site da Oficina - pactuamos com os participantes da Oficina que os achados estariam disponíveis em uma área virtual.  
- [x]  Estabelecer metas de publicação: 3 por dia? 15 por semana? @Clarisse1983 @edmirandajr 
- [x]  Levar a pauta (notificações x defeso eleitoral) para reunião estratégica. 
- [x] Estabelecer fluxo de comunicação dos times de Dev e Design para o time de Narrativas, no que diz respeito a: novas funcionalidades (Elmo, Mapa, iSUS...); novas inscrições (Mapa). @thaistoscano @victorMagalhaesPacheco 

- [ ] Demandar na sprint integrada a automação das notificações de inscrições no Mapa em três momentos: abertura das inscrições, proximidade do fim das inscrições, último dia de inscrições. @thaistoscano 
- [x] Alinhar previamente com Roberto (Jurídico) e com a Casa Civil (Alice nos alertou sobre a necessidade, durante a reunião estratégica). 
- [x] Apresentar a Alice nossa proposta. 
- [x] Alice deverá marcar agenda com Narrativas, Ascom e Superintendente. 
- [ ] Alinhar com a Ariane: vamos complementar um papel que já é deles, sem tirar deles essa função, pricipalmente no que diz respeito ao fluxo de demandas da Escola, que continua sendo: ASCOm como responsável pelas notificações do iSUS, qualquer setor demanda pra eles, a não ser a gente, que publica direto e de forma automatizada.

--------------
https://docs.google.com/document/d/1cmrgBl8ZxJAs_Wc-bUYNBjet1Vvbe-dnE45g36E-Q8E/edit

**Comment by ClarisCaval** [comment]
Apresentamos a proposta de seguir fazendo notificações apesar do defeso na última estratégica, sexta 12, e vamos apresentar uma proposta mais direcionada para Alice, que deverá levar a questão para o comitê de governança.

**Comment by ericabpinho** [comment]
Observe: 
- Percebemos que a comunicação sobre o site da Oficina deveria ser feita diretamente aos participantes interessados, pelo e-mail institucional. @edmirandajr criará issue. 
- Percebemos que a periodicidade de 15x/semana seria excessiva e decidimos, por enquanto, ir decidindo conforme a demanda.
