### ISSUE TITLE
Produzir apresentação impressa do roadmap

### ISSUE THREAD

**Issue by ericabpinho** [EscolaDeSaudePublica/DesignLab#377]
## **Objetivo**

**Como** Pessoa do Comitê de Governança da ESP
**Quero** Visualizar o roadmap da board integrada
**Para** Compreender a linha do tempo de entregas do laboratório até dezembro

## **Contexto**

-Desde junho de 2022, o Felicilab  mudou sua forma de organização de trabalho, substituindo a divisão em times pelo esforço concentrado da board integrada. A integração de esforços de diferentes times possibilita que o laboratório como um todo esteja focado nos desafios transversais da ESP/CE - os problemas que afetam mais de uma área. Entre outros resultados, o trabalho da board integrada viabilizou a construção de um roadmap, uma linha do tempo das entregas a serem feitas até dezembro de 2022, conforme os critérios de priorização validados em processos anteriores. 

- Na reunião do Comitê de Governança desta quinta-feita, dia 04/08/2022, o roadmap será apresentado para a ESP/CE. Por isso, estamos preparando uma versão impressa deste documento. 

## **Escopo**

- [ ] Alinhar com Jorge o formato e textos. 
- [ ] Preparação da arte - @elpadrejorge 
- [ ] Validação final com @ricardopoppi. 
- [ ] Imprimir. 
- [ ] Entregar o impresso para Alice levar para a reunião. 

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** Participo da reunião do Comitê de Governança. 
**Quando** Preciso apresentar a linha do tempo de entregas do Felicilab.
**então** Apresento a versão simplificada do roadmap. 

## Observações
Links de apoio e informações adicionais
