### ISSUE TITLE
Plataforma de Qualificação da Força de Trabalho do SUS-CE

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#80]
## **Objetivo**

**Como** designer  
**Quero** contribuir com a estruturação
**Para** fortalecimento da experiência do usuário e estratégias do SUS-CE

## **Contexto**

A Plataforma de Qualificação da Força de Trabalho do SUS-CE é um conjunto de ferramentas estratégicas que visam contribuir para o Mapeamento, Diagnóstico e Educação dos Trabalhadores da Saúde no estado do Ceará. Através dela, será possível gerar indicadores para norteamento da Gestão Estratégica e apoio à tomada de decisão sobre: distribuição demográfica, níveis de especialização, níveis de qualificação, áreas com fragilidades de qualificação, eficácia de estratégias de qualificação e gestão de carreira.

## **Escopo**

- [ ] Fluxo de Cadastro (Integração de dados entre iDSaúde, iSUS e Mapa da Saúde)
- [ ] QualiQuiz (Ferramenta de Avaliação e Qualificação dos Trabalhadores da Saúde do SUS-CE)
- [ ] Mapa da Saúde
- [ ] Sagu
- [ ] RPES
- [ ] ESP Virtual

## Observações
https://www.figma.com/file/MNWHYXV7uXZP7ti98mrn6a/Arquitetura-da-Plataforma?node-id=0%3A1

**Comment by RaniGub** [comment]
Esse épico precisa ser refinado com o time de Gestão. @gabrieladamarques @wforte88
