### ISSUE TITLE
Assistente Virtual SUSi

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#81]
## **Objetivo**

**Como** designer  
**Quero** contribuir com o conceito de uma Assistente Virtual
**Para** integrar e consolidar a experiência das pessoas usuárias nas Soluções Digitais do SUS-CE

## **Contexto**

A SUSi é a Assistente Virtual das soluções digitais em saúde do SUS-CE e tem como objetivo tornar a jornada da pessoa usuária uma experiência mais fluída, com narrativa sólida e integrada.

## **Escopo**

MVP 1
- [ ] Desenvolver a AI da SUSi
- [ ] Definir o conceito da SUSi
- [ ] Definir a persona
- [ ] Definir comportamentos possíveis
- [ ] Definir os pontos de contato com as pessoas usuárias
- [ ] Refinar com stakeholders
- [ ] Definir seu design (visual)
- [ ] Definir as variações de design com base nas ações da pessoa usuária
- [ ] Refinar com stakeholders
- [ ] Desenvolver animações para seus comportamentos
- [ ] Prototipar uma experiência
- [ ] Refinar com stakeholders
- [ ] Prototipar a experiência no Fluxo de Cadastro (iDSaúde)

## **Critérios de Aceitação**

**Dado que** a pessoa usuária 
**Quando** execute uma ação na tela    
**então** a SUSi retorne uma interação com informações

## Observações
Links de apoio e informações adicionais

**Comment by uira** [comment]
@RaniGub 😍😍😍😍

**Comment by uira** [comment]
Isso aqui é um projeto, de Pesquisa e Desenvolvimento Completo.

@gabrieladamarques e @wforte88 , acho que vale a pena entrar como uma iniciativa dentro do projeto do iSUS, fortalecendo a idéia de "Plataforma"

@RaniGub consegue estimar tempo e recursos para essas ativiades?

**Comment by uira** [comment]
@RaniGub , vale atualizar a descrição da história com o briefing dessa issue: https://github.com/EscolaDeSaudePublica/BancoDeIDeias/issues/1

E atualizar, com a narrativa e evolução conceitual, de que a Susi é uma criatura transdimensional que veio do futuro pra nos conectar ao MetaVerso da Saúde ;)

**Comment by RaniGub** [comment]
> Isso aqui é um projeto, de Pesquisa e Desenvolvimento Completo.
> 
> @gabrieladamarques e @wforte88 , acho que vale a pena entrar como uma iniciativa dentro do projeto do iSUS, fortalecendo a idéia de "Plataforma"
> 
> @RaniGub consegue estimar tempo e recursos para essas ativiades?

A ideia é que no MVP 1 ela não seja animada e esteja presente no Fluxo de Cadastro Integrado. Da conceituação às telas de protótipo, acredito que uns 2 meses. Imagino que precisamos de um ilustrador, um designer de serviço e um ux designer.

**Comment by RaniGub** [comment]
> @RaniGub , vale atualizar a descrição da história com o briefing dessa issue: [EscolaDeSaudePublica/BancoDeIDeias#1](https://github.com/EscolaDeSaudePublica/BancoDeIDeias/issues/1)
> 
> E atualizar, com a narrativa e evolução conceitual, de que a Susi é uma criatura transdimensional que veio do futuro pra nos conectar ao MetaVerso da Saúde ;)

Ah sim, mais uma pessoa para adaptar e atualizar a narrativa.

**Comment by RaniGub** [comment]
teste
