### ISSUE TITLE
Consolidação das informações | Oficina de Design de Serviços Públicos

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#86]
## **Objetivo**

**Como** designer  
**Quero** consolidar as informações da Oficina de DSP
**Para** compartilhar a visualizações dos resultados com os participantes

## **Contexto**

Na Oficina de Design de Serviços Públicos foi possível vislumbrar uma série de integrações entre as possíveis soluções da Agenda de Prioridades 2021-2022 da Sepos. Em vista disso, faz-se necessário a consolidação das informações em um único documento contributivo para norteamento e tomada de decisões da gestão das Políticas do SUS-CE.

## **Escopo**

De 16/08 a 20/08
- [x] Consolidar as informações das Árvores de Problemas
- [x] Consolidar as informações das Inceptions
- [x] Consolidar duas pétalas ausentes na Mandala de Governança
- [x] Consolidar as informações das Mandalas da Governança Colaborativa

De 23/08 a 27/08
- [x] Estruturação do artefato impresso
- [x] Feedback dos participantes
- [x] Reunião de avaliação sobre Oficina DSP

De 13/09 a 27/09
- [x] Compartilhar a visualização da Board da Oficina com participantes (View only)
- [x] Validar as informações com Uirá
- [x] Fazer ajustes 1
- [x] Revisão Sara
- [x] Validar as informações com Uirá
- [x] Fazer ajustes 2
- [x] Solicitar impressão do artefato
- [x] Desenvolver certificado (Mapas da Saúde?)

04/10
- [x] Solicitação de avaliação pelo Conselho Editorial

## Observações
https://www.figma.com/file/Avf3SQNDfeglilqOoXXVEY/Agenda-de-Prioridades-2021-2022-SEPOS?node-id=0%3A1

**Comment by RaniGub** [comment]
Em conversa com a @gabrieladamarques em 01/12/2021, entendemos que a tarefa 'Relacionamento das soluções no AirTable' estaria vinculada ao time de Gestão de Projetos. Então foi suprimida desse épico.
