### ISSUE TITLE
Taxonomia

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#87]
## **Objetivo**

**Como** designer  
**Quero** mapear taxonomias
**Para** nortear os campos do Fluxo de Cadastro

## **Contexto**

No contexto do Fluxo de Cadastro, é necessário mapear e relacionar a taxonomia de diferentes Soluções Digitais e para que seja alinhado quais campos serão apresentados para a pessoa usuária em sua jornada.

## **Escopo**

- [x] 1 Relacionar campos das Soluções Digitais
- [x] 1.1 Relacionar campos do CNES
- [x] 1.2 Relacionar campos da SESA
- [x] 1.3 Relacionar campos do CNPq (Lattes)
- [x] 1.4 Relacionar campos do Sagu
- [x] 1.5 Relacionar campo do Mapa da Saúde
- [x] 1.6 Relacionar campos do iSUS e idSaúde
- [x] 1.7 Relacionar campos CEP, Logradouro, Número e Complemento (Victor)
- [ ] 2 Levantar opções que estarão disponíveis em cada campo
- [ ] 2.1 Definir a fonte de onde foram retiradas as opções
- [ ] Contextualização sobre Ontologia e Taxonomia (Paulo)
- [ ] Refinamento com Uirá

## Observações
https://docs.google.com/spreadsheets/d/1-DciWMy2V5icyfjjJ42HdTjulBSx-emParbLcuy29WA/edit?usp=sharing

**Comment by RaniGub** [comment]
Conversarei com o @wforte88 para dar o contexto de onde pausamos.
