### ISSUE TITLE
AI - Mapa da Saúde (V1.1)

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/DesignLab#88]
## **Objetivo**

**Como** designer  
**Quero** fazer o levantamento da AI do Mapa da Saúde
**Para** nortear uma nova experiência para pessoa usuária

## **Contexto**

Considerando o relacionamento de taxonomia do Fluxo de Cadastro (#87), faz-se necessário o levantamento da atual AI do Mapa da Saúde. As informações terão relevância tanto para o relacionamento dos campos nas diversas soluções digitais quanto para a nova proposta da AI do Mapa da Saúde.  

## **Escopo**

- [x] 1 Fazer o levantamento da AI do Mapa da Saúde
- [x] 1.1 AI de nível 1 das opções do Menu Superior
- [x] 1.2 AI de nível 2 das opções do Menu Superior
- [x] 1.2.1 Mapear a jornada de Agentes
- [x] 1.2.2 Mapear a jornada de Espaços
- [x] 1.2.3 Mapear a jornada de Projetos
- [x] 1.2.4 Mapear a jornada de Oportunidades
- [x] 1.2.5 Mapear a jornada de Editais
- [x] 2 AI das Configurações
- [x] 2.1 Opção 'Painel de Controle'
- [x] 2.1.1 Modo de visualização
- [x] 2.1.2 Modo de edição
- [x] 2.2 Opção 'Meu Perfil'
- [x] 2.2.1 Modo de visualização
- [x] 2.2.1.1 Aba Sobre
- [x] 2.2.1.2 Aba Agenda
- [x] 2.2.1.3 Aba Responsáveis
- [x] 2.2.1.4 Aba Espaços
- [x] 2.2.1.5 Aba Oportunidades
- [x] 2.2.2 Modo de edição
- [x] 2.2.2.1 Aba Sobre
- [x] 2.2.2.2 Aba Agenda
- [x] 2.2.2.3 Aba Responsáveis
- [x] 2.2.2.4 Aba Espaços
- [x] 2.2.2.5 Aba Oportunidades
- [x] 2.3 Opção 'Meus Agentes'
- [x] 2.3.1 Modo de visualização
- [x] 2.3.2 Modo de edição
- [x] 2.4 Opção 'Meus Eventos'
- [x] 2.4.1 Modo de visualização
- [x] 2.4.2 Modo de edição
- [x] 2.5 Opção 'Meus Espaços'
- [x] 2.5.1 Modo de visualização
- [x] 2.5.2 Modo de edição
- [x] 2.6 Opção 'Meus Projetos'
- [x] 2.6.1 Modo de visualização
- [x] 2.6.2 Modo de edição
- [x] 2.7 Opção 'Minhas Oportunidades'
- [x] 2.7.1 Modo de visualização
- [x] 2.7.2 Modo de edição
- [x] 2.8 Opção 'Minhas Inscrições'
- [x] 2.9 Opção 'Meus Recursos'
- [x] 2.10 Opção 'Meus Apps'
- [x] 2.11 Opção 'Meus Selos'
- [x] Organização das Labels
- [x] Relacionamento com tarefas do Repositório do DevLab desde 16/08/2021
- [x] Momento com stakeholders 1
- [x] Resolução de dúvidas após momento com stakeholders 1
- [x] Identificar na AI quais são os campos que serão relacionados com a taxonomia das Soluções Digitais

## Observações
https://www.figma.com/file/FppwWzm8uRDd69W2y4fhLm/AI-Mapa-da-Sa%C3%BAde?node-id=0%3A1

**Comment by RaniGub** [comment]
AI de nível 1 das opções de Menu mapeada. Iniciando mapeamento do perfil no modo de visualização e edição. Após, mapeamento da AI de nível 2 das opções de Menu (quando a pessoa usuária acessa um registro).

**Comment by RaniGub** [comment]
AI do perfil no modo de visualização completada. Iniciando modo de edição.

**Comment by RaniGub** [comment]
Ai da Aba 'Sobre' e 'Responsáveis', concluída. Ficou pendente a organização das Categorias Profissionais e Especialidades pois um bug foi identificado. @victorMagalhaesPacheco está ciente e já trabalhando na solução. Tão logo solucionado, a organização será relativamente rápida, pois todos os campos já foram mapeados anteriormente. Iniciando AI de 'Oportunidades' no modo de edição.

**Comment by RaniGub** [comment]
AI no modo de visualização da Aba 'Oportunidades' (da opção 'Meu Perfil') concluído. É importante frisar que são opções diferentes do modo de edição e da aba 'Minhas Oportunidades'. Modo de edição já em mapeamento.

**Comment by RaniGub** [comment]
Categorias e Especialidades da aba 'Sobre', Modo de edição, Tela 'Meu Perfil', atualizada com base no link https://github.com/EscolaDeSaudePublica/Saude/issues/9 A especialidade Arqueologia (Categoria Ciências Sociais e Humanas) e Meteorologia (Categoria Meio Ambiente) não foi identificada nas especialidades atuais do Mapa. Observação feita na AI.
